# -*- coding: utf-8 -*-
"""UC Question Sprint - Akshaya Kamalakannan, Anya Agarwal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKNt-0KH_QJ6mzt9QnaPi-MYEy8nJEZ5
"""

import pandas as pd

df_add_summary = pd.read_csv("bay_area_modeling_table.csv")

# Calculate white admit rate
# Avoid division by zero by filtering out rows where app_white is 0
df_add_summary['white_admit_rate'] = df_add_summary.apply(lambda row: row['adm_white'] / row['app_white'] if row['app_white'] != 0 else 0, axis=1)

# Apply the filters with the corrected 'campus' value
white_admit_data = df_add_summary[
    (df_add_summary['fall_term'] == 2025) &
    (df_add_summary['campus'] == 'Universitywide')
]

# Display the relevant columns or the average white admit rate for the filtered data
print("Filtered data (first 5 rows) and white admit rate:")
print(white_admit_data[['fall_term', 'campus', 'adm_white', 'app_white', 'white_admit_rate']].head())

print(f"\nAverage white admit rate for Fall Term 2025, Universitywide Campus: {white_admit_data['white_admit_rate'].mean():.2f}")

df_add_summary['hispanic_latino_admit_rate'] = df_add_summary.apply(lambda row: row['adm_hispanic_latinx'] / row['app_hispanic_latinx'] if row['app_hispanic_latinx'] != 0 else 0, axis=1)

hispanic_latino_admit_data = df_add_summary[
    (df_add_summary['fall_term'] == 2025) &
    (df_add_summary['campus'] == 'Universitywide')
]

print(f"\nAverage hispanic/latino(a) admit rate for Fall Term 2025, Universitywide Campus: {hispanic_latino_admit_data['hispanic_latino_admit_rate'].mean():.2f}")

# Fall 2025 admit rate at UCLA for applicants from California public high schools.

# Filter for Fall 2025 and Public High Schools
admit_rate_2025_public_schools = df_add_summary[
    (df_add_summary['fall_term'] == 2025) &
    (df_add_summary['school_type'] == 'High Schools (Public)')
]

# Further filter for UCLA campus
ucla_public_school_data = admit_rate_2025_public_schools[
    admit_rate_2025_public_schools['campus'] == 'Los Angeles'
]

if not ucla_public_school_data.empty:
    total_admits = ucla_public_school_data['admits'].sum()
    total_applicants = ucla_public_school_data['applicants'].sum()

    if total_applicants > 0:
        ucla_admit_rate = total_admits / total_applicants
        print(f"The Fall 2025 admit rate at UCLA for applicants from California public high schools is: {ucla_admit_rate:.2%}")
    else:
        print("No applicants found for UCLA from California public high schools in Fall 2025.")
else:
    print("No data found for UCLA from California public high schools in Fall 2025.")

# In fall 2025, at how many of the 9 UC campuses was the White freshman admit rate HIGHER than the Hispanic/Latino(a) admit rate?

df_ethnicity = pd.read_csv("uc_admissions_summary_by_ethnicity.csv")

# at berkeley
bfall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Berkeley') & (df_ethnicity['ethnicity'] == 'White')]
bfall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Berkeley') & (df_ethnicity['ethnicity'] == 'White')]
bfall2025_white_freshman_admit_rate = bfall2025_white_adm['n'].sum() / bfall2025_white_app['n'].sum()

bfall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Berkeley') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
bfall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Berkeley') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
bfall2025_latinx_freshman_admit_rate = bfall2025_latinx_adm['n'].sum() / bfall2025_latinx_app['n'].sum()

# at davis
dfall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Davis') & (df_ethnicity['ethnicity'] == 'White')]
dfall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Davis') & (df_ethnicity['ethnicity'] == 'White')]
dfall2025_white_freshman_admit_rate = dfall2025_white_adm['n'].sum() / dfall2025_white_app['n'].sum()

dfall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Davis') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
dfall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Davis') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
dfall2025_latinx_freshman_admit_rate = dfall2025_latinx_adm['n'].sum() / dfall2025_latinx_app['n'].sum()

# at irvine
ifall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Irvine') & (df_ethnicity['ethnicity'] == 'White')]
ifall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Irvine') & (df_ethnicity['ethnicity'] == 'White')]
ifall2025_white_freshman_admit_rate = ifall2025_white_adm['n'].sum() / ifall2025_white_app['n'].sum()

ifall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Irvine') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
ifall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Irvine') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
ifall2025_latinx_freshman_admit_rate = ifall2025_latinx_adm['n'].sum() / ifall2025_latinx_app['n'].sum()

# at Los Angeles
lafall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Los Angeles') & (df_ethnicity['ethnicity'] == 'White')]
lafall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Los Angeles') & (df_ethnicity['ethnicity'] == 'White')]
lafall2025_white_freshman_admit_rate = lafall2025_white_adm['n'].sum() / lafall2025_white_app['n'].sum()

lafall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Los Angeles') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
lafall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Los Angeles') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
lafall2025_latinx_freshman_admit_rate = lafall2025_latinx_adm['n'].sum() / lafall2025_latinx_app['n'].sum()

# at Merced
mfall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Merced') & (df_ethnicity['ethnicity'] == 'White')]
mfall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Merced') & (df_ethnicity['ethnicity'] == 'White')]
mfall2025_white_freshman_admit_rate = mfall2025_white_adm['n'].sum() / mfall2025_white_app['n'].sum()

mfall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Merced') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
mfall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Merced') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
mfall2025_latinx_freshman_admit_rate = mfall2025_latinx_adm['n'].sum() / mfall2025_latinx_app['n'].sum()

# at Riverside
rfall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Riverside') & (df_ethnicity['ethnicity'] == 'White')]
rfall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Riverside') & (df_ethnicity['ethnicity'] == 'White')]
rfall2025_white_freshman_admit_rate = rfall2025_white_adm['n'].sum() / rfall2025_white_app['n'].sum()

rfall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Riverside') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
rfall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Riverside') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
rfall2025_latinx_freshman_admit_rate = rfall2025_latinx_adm['n'].sum() / rfall2025_latinx_app['n'].sum()

# at San Diego
sdfall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'San Diego') & (df_ethnicity['ethnicity'] == 'White')]
sdfall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'San Diego') & (df_ethnicity['ethnicity'] == 'White')]
sdfall2025_white_freshman_admit_rate = sdfall2025_white_adm['n'].sum() / sdfall2025_white_app['n'].sum()

sdfall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'San Diego') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
sdfall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'San Diego') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
sdfall2025_latinx_freshman_admit_rate = sdfall2025_latinx_adm['n'].sum() / sdfall2025_latinx_app['n'].sum()

# at Santa Barbara
sbfall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Santa Barbara') & (df_ethnicity['ethnicity'] == 'White')]
sbfall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Santa Barbara') & (df_ethnicity['ethnicity'] == 'White')]
sbfall2025_white_freshman_admit_rate = sbfall2025_white_adm['n'].sum() / sbfall2025_white_app['n'].sum()

sbfall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Santa Barbara') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
sbfall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Santa Barbara') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
sbfall2025_latinx_freshman_admit_rate = sbfall2025_latinx_adm['n'].sum() / sbfall2025_latinx_app['n'].sum()

# at Santa Cruz
scfall2025_white_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Santa Cruz') & (df_ethnicity['ethnicity'] == 'White')]
scfall2025_white_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Santa Cruz') & (df_ethnicity['ethnicity'] == 'White')]
scfall2025_white_freshman_admit_rate = scfall2025_white_adm['n'].sum() / scfall2025_white_app['n'].sum()

scfall2025_latinx_app = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'App') & (df_ethnicity['campus'] == 'Santa Cruz') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
scfall2025_latinx_adm = df_ethnicity[(df_ethnicity['entrant_level'] == 'freshman') & (df_ethnicity['fall_term'] == 2025) & (df_ethnicity['count_type'] == 'Adm') & (df_ethnicity['campus'] == 'Santa Cruz') & (df_ethnicity['ethnicity'] == 'Hispanic/Latino(a)')]
scfall2025_latinx_freshman_admit_rate = scfall2025_latinx_adm['n'].sum() / scfall2025_latinx_app['n'].sum()

print(scfall2025_white_freshman_admit_rate)

# How do the yield rates (enrolled/accepted) change for charter vs. non-charter schools for fall 2023 through fall 2025?

dashboard_data = pd.read_csv("dashboard_data.csv")

# 2025
charter_school_2025 = dashboard_data[(dashboard_data['charter'] == 'Y') & (dashboard_data['fall_term'] == 2025)].copy()
non_charter_school_2025 = dashboard_data[(dashboard_data['charter'] == 'N') & (dashboard_data['fall_term'] == 2025)].copy()

yrcs_2025 = charter_school_2025['enrolled_rate2025'] = charter_school_2025['enrollees'].sum() / charter_school_2025['admits'].sum()
yrncs_2025 = non_charter_school_2025['enrolled_rate2025'] = non_charter_school_2025['enrollees'].sum() / non_charter_school_2025['admits'].sum()

print(yrcs_2025)
print(yrncs_2025)
print(" ")

# 2024
charter_school_2024 = dashboard_data[(dashboard_data['charter'] == 'Y') & (dashboard_data['fall_term'] == 2024)].copy()
non_charter_school_2024 = dashboard_data[(dashboard_data['charter'] == 'N') & (dashboard_data['fall_term'] == 2024)].copy()

yrcs_2024 = charter_school_2024['enrolled_rate2024'] = charter_school_2024['enrollees'].sum() / charter_school_2024['admits'].sum()
yrncs_2024 = non_charter_school_2024['enrolled_rate2024'] = non_charter_school_2024['enrollees'].sum() / non_charter_school_2024['admits'].sum()

print(yrcs_2024)
print(yrncs_2024)
print(" ")

# 2023
charter_school_2023 = dashboard_data[(dashboard_data['charter'] == 'Y') & (dashboard_data['fall_term'] == 2023)].copy()
non_charter_school_2023 = dashboard_data[(dashboard_data['charter'] == 'N') & (dashboard_data['fall_term'] == 2023)].copy()

yrcs_2023 = charter_school_2023['enrolled_rate2023'] = charter_school_2023['enrollees'].sum() / charter_school_2023['admits'].sum()
yrncs_2023 = non_charter_school_2023['enrolled_rate2023'] = non_charter_school_2023['enrollees'].sum() / non_charter_school_2023['admits'].sum()

print(yrcs_2023)
print(yrncs_2023)

"""# New Section"""

#At Mission San Jose High School in fall 2023, what share of the school's a-g completers applied to at least one UC? (Universitywide `applicants` divided by `ag_completers`)

import pandas as pd

df = pd.read_csv("dashboard_data (1).csv")

mission_data = df[(df['fall_term'] == 2023) & (df['high_school'] == 'MISSION SAN JOSE HIGH SCHOOL') & (df['campus'] == 'Universitywide')]

if not mission_data.empty:
  appys = mission_data['peer_applicants'].iloc[0]
  completers = mission_data['peer_ag_completers'].iloc[0]

  Atleast_OneUC = appys / completers
  print("The share of Mission San Jose's a-g completers in fall of 2023 who applied to atleast one UC is ")
  print(Atleast_OneUC*100)
  print("%.")

#Of Bay Area high school graduates in the class of 2023, what share enrolled at a California Community College within 12 months?
import pandas as pd

df1 = pd.read_csv("bay_area_modeling_table (1).csv")
df2 = pd.read_csv("dashboard_data (1).csv")

hischool_data = df1[(df1['fall_term'] == 2023) & (df1['campus'] == 'Universitywide') & (df1['school_type'] == 'High Schools (Public)')]

hischool_data_2 = df2[(df2['fall_term'] == 2023) & (df2['campus'] == 'Universitywide') & (df2['school_type'] == 'High Schools (Public)')]


total_grads = hischool_data_2['peer_cohort_students'].sum()
ccc_people = hischool_data['enrolled_ccc'].sum()
print("The share of Bay Area high school graduates in the class of 2023 who enrolled at a California Community College within 12 months is ")
print(ccc_people/total_grads * 100)
print("%.")

#How many distinct California public high schools sent at least one freshman applicant to UC in fall 2025?
import pandas as pd

df2 = pd.read_csv("dashboard_data (1).csv")

hischool_data_2 = df2[(df2['fall_term'] == 2025) & (df2['campus'] == 'Universitywide') & (df2['school_type'] == 'High Schools (Public)') & (df2['admits'] != 0)]

row_count = len(hischool_data_2)
print(row_count)

#Fall 2025: at which UC campus does applying to Computer Science cost the most admit rate, versus that campus's overall admit rate?
import pandas as pd

df = pd.read_csv("uc_freshman_admission_by_discipline (1).csv")

allowed_entries = ['All disciplines', 'Computer Science']
compsci = df[df['broad_discipline'].isin(allowed_entries)]

pivoted_compsci = compsci.pivot(index='campus', columns='broad_discipline', values='admit_rate').reset_index()

pivoted_compsci['cut_difference'] = pivoted_compsci['All disciplines'] - pivoted_compsci['Computer Science']

sorted_df = pivoted_compsci.sort_values(by='cut_difference', ascending = False)
print (sorted_df)

#Five schools are listed on the answer form. Using UC Berkeley 2022-2025, which one most OUTPERFORMS its expected admit rate, after controlling for a-g completion, poverty, applicant GPA and school size?

import pandas as pd

df = pd.read_csv("dashboard_data (1).csv")

mission_data = df[(df['fall_term'] == 2023) & (df['high_school'] == 'MISSION SAN JOSE HIGH SCHOOL') & (df['campus'] == 'Universitywide')]
print(mission_data)